# Header
menu:
  首页: /
  存档: /archives
  分类: /categories
  标签: /tags
  留言: /guestbook
  关于: /about

# Profile
profile:
  name: Haizs Chen
  title: Independent Developer
  location: China
  # Social
  mail: mailto:mail@haizs.net
  github: Https://Github.com/Haizs
  feed: /atom.xml


# Footer
nav:
  站点地图: /sitemap.xml
  主题源码: https://Github.com/Haizs/hexo-theme-hai
  海之工作室: https://haizs.net

# Miscellaneous
favicon: /images/favicon.ico