title:
  archive: 存档
  category: 分类
  tag: 标签

widget:
  catalogue: 文章目录
  archives: 文章归档
  categories: 顶级分类
  tagcloud: 常用标签
  recents: 最新文章
  links: 友情链接

calendar:
  sunday: 日
  monday: 月
  tuesday: 火
  wednesday: 水
  thursday: 木
  friday: 金
  saturday: 土